from pymongo import MongoClient
from dotenv import load_dotenv
import os

load_dotenv()

# Connect to MongoDB (default local connection)
client = MongoClient(os.getenv("MONGO_URI"))

# Database and Collection
db = client["customer_db"]
collection = db["churn_data"]

# Customer data as dictionaries
customers = [
    {
        "CustomerID": "7561-EFGH",
        "Name": "Isabella Perez",
        "Count": 1,
        "Country": "United States",
        "State": "California",
        "City": "Los Angeles",
        "Zip Code": 90049,
        "Lat Long": "33.985452, -118.412742",
        "Latitude": 33.985452,
        "Longitude": -118.412742,
        "Gender": "Male",
        "Senior Citizen": "No",
        "Partner": "No",
        "Dependents": "Yes",
        "Tenure Months": 62,
        "Phone Service": "No",
        "Multiple Lines": "Yes",
        "Internet Service": "Fiber optic",
        "Online Security": "No",
        "Online Backup": "Yes",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "No",
        "Streaming Movies": "No",
        "Contract": "Two year",
        "Paperless Billing": "No",
        "Payment Method": "Mailed check",
        "Monthly Charges": 99.45,
        "Total Charges": 6165.9,
        "CLTV": 6589,
        "Quarter": "Q4",
        "Referred a Friend": "Yes",
        "Number of Referrals": 0,
        "Tenure in Months": 62,
        "Offer": "Offer B",
        "Phone Service_services": "No",
        "Avg Monthly Long Distance Charges": 30.69,
        "Multiple Lines_services": "Yes",
        "Internet Service_services": "Fiber optic",
        "Internet Type": "Fiber optic",
        "Avg Monthly GB Download": 24,
        "Online Security_services": "No",
        "Online Backup_services": "Yes",
        "Device Protection Plan": "No",
        "Premium Tech Support": "No",
        "Streaming TV_services": "No",
        "Streaming Movies_services": "Yes",
        "Streaming Music": "Yes",
        "Unlimited Data": "Yes",
        "Contract_services": "Two year",
        "Paperless Billing_services": "No",
        "Payment Method_services": "Mailed check",
        "Monthly Charge": 99.45,
        "Total Charges_services": 6165.9,
        "Total Refunds": 10.26,
        "Total Extra Data Charges": 2,
        "Total Long Distance Charges": 1902.78,
        "Total Revenue": 8068.68,
        "Quarter_status": "Q4",
        "Satisfaction Score": 3,
        "CLTV_status": "Active"
    },
    {
        "CustomerID": "8245-IJKL",
        "Name": "Daniel Garcia",
        "Count": 1,
        "Country": "United States",
        "State": "California",
        "City": "Los Angeles",
        "Zip Code": 90083,
        "Lat Long": "34.143627, -118.245839",
        "Latitude": 34.143627,
        "Longitude": -118.245839,
        "Gender": "Male",
        "Senior Citizen": "Yes",
        "Partner": "Yes",
        "Dependents": "Yes",
        "Tenure Months": 54,
        "Phone Service": "No",
        "Multiple Lines": "No",
        "Internet Service": "DSL",
        "Online Security": "Yes",
        "Online Backup": "No",
        "Device Protection": "Yes",
        "Tech Support": "No",
        "Streaming TV": "No",
        "Streaming Movies": "No",
        "Contract": "Month-to-month",
        "Paperless Billing": "Yes",
        "Payment Method": "Credit card (automatic)",
        "Monthly Charges": 58.72,
        "Total Charges": 3170.88,
        "CLTV": 2602,
        "Quarter": "Q2",
        "Referred a Friend": "Yes",
        "Number of Referrals": 3,
        "Tenure in Months": 54,
        "Offer": "Offer B",
        "Phone Service_services": "No",
        "Avg Monthly Long Distance Charges": 6.63,
        "Multiple Lines_services": "No",
        "Internet Service_services": "DSL",
        "Internet Type": "DSL",
        "Avg Monthly GB Download": 32,
        "Online Security_services": "Yes",
        "Online Backup_services": "No",
        "Device Protection Plan": "Yes",
        "Premium Tech Support": "No",
        "Streaming TV_services": "No",
        "Streaming Movies_services": "No",
        "Streaming Music": "Yes",
        "Unlimited Data": "Yes",
        "Contract_services": "Month-to-month",
        "Paperless Billing_services": "Yes",
        "Payment Method_services": "Credit card (automatic)",
        "Monthly Charge": 58.72,
        "Total Charges_services": 3170.88,
        "Total Refunds": 66.32,
        "Total Extra Data Charges": 17,
        "Total Long Distance Charges": 358.02,
        "Total Revenue": 3528.9,
        "Quarter_status": "Q2",
        "Satisfaction Score": 1,
        "CLTV_status": "Active"
    },
    {
        "CustomerID": "4734-QRST",
        "Name": "Mia Hernandez",
        "Count": 1,
        "Country": "United States",
        "State": "California",
        "City": "Los Angeles",
        "Zip Code": 90051,
        "Lat Long": "34.01097, -118.39514",
        "Latitude": 34.01097,
        "Longitude": -118.39514,
        "Gender": "Female",
        "Senior Citizen": "No",
        "Partner": "No",
        "Dependents": "Yes",
        "Tenure Months": 45,
        "Phone Service": "Yes",
        "Multiple Lines": "Yes",
        "Internet Service": "Fiber optic",
        "Online Security": "Yes",
        "Online Backup": "No",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "Yes",
        "Streaming Movies": "Yes",
        "Contract": "One year",
        "Paperless Billing": "No",
        "Payment Method": "Electronic check",
        "Monthly Charges": 118.85,
        "Total Charges": 5348.25,
        "CLTV": 4998,
        "Quarter": "Q4",
        "Referred a Friend": "Yes",
        "Number of Referrals": 4,
        "Tenure in Months": 45,
        "Offer": "Offer A",
        "Phone Service_services": "Yes",
        "Avg Monthly Long Distance Charges": 17.91,
        "Multiple Lines_services": "Yes",
        "Internet Service_services": "Fiber optic",
        "Internet Type": "Fiber optic",
        "Avg Monthly GB Download": 7,
        "Online Security_services": "Yes",
        "Online Backup_services": "No",
        "Device Protection Plan": "No",
        "Premium Tech Support": "No",
        "Streaming TV_services": "Yes",
        "Streaming Movies_services": "Yes",
        "Streaming Music": "Yes",
        "Unlimited Data": "Yes",
        "Contract_services": "One year",
        "Paperless Billing_services": "No",
        "Payment Method_services": "Electronic check",
        "Monthly Charge": 118.85,
        "Total Charges_services": 5348.25,
        "Total Refunds": 78.57,
        "Total Extra Data Charges": 3,
        "Total Long Distance Charges": 805.95,
        "Total Revenue": 6154.2,
        "Quarter_status": "Q4",
        "Satisfaction Score": 2,
        "CLTV_status": "Active"
    }
]

# Insert into MongoDB
insert_result = collection.insert_many(customers)

# Print inserted IDs
print("Inserted IDs:", insert_result.inserted_ids)